### ISSUE TITLE
Error: Socket unusable after connection

### ISSUE THREAD

**Issue by danpe** [argon/node-apn#238]
```javascript
var apnOptions = {
        pfx: "./config/apns_production_certificate.p12",          
        passphrase: "asdasdasd@123",                               
};
```

Than when I'm trying to send notification the server crashes with the following:

```javascript
node_modules/apn/node_modules/q/q.js:128
                    throw e;
                          ^
Error: Socket unusable after connection. Hint: You may be using a certificate for the wrong environment
    at Connection.connect.delay.then.fail.delay (/Users/danpeleg/Projects/GlobKeeper/globkeeper-server/node_modules/apn/lib/connection.js:224:10)
    at _fulfilled (/Users/danpeleg/Projects/GlobKeeper/globkeeper-server/node_modules/apn/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Users/danpeleg/Projects/GlobKeeper/globkeeper-server/node_modules/apn/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/Users/danpeleg/Projects/GlobKeeper/globkeeper-server/node_modules/apn/node_modules/q/q.js:756:13)
    at /Users/danpeleg/Projects/GlobKeeper/globkeeper-server/node_modules/apn/node_modules/q/q.js:564:44
    at flush (/Users/danpeleg/Projects/GlobKeeper/globkeeper-server/node_modules/apn/node_modules/q/q.js:110:17)
    at process._tickDomainCallback (node.js:463:13)
```

I'm using a Production Certificate and NODE_ENV=production.

What is wrong ?

**Comment by Tarang** [comment]
I have this issue too. The app works consistently in dev mode, and has this problem consistently in production mode.

I'm not entirely sure how node-apn grants relevance to the mode the application is running in? Is there a way to make it 'just work' all the time?

**Comment by argon** [comment]
Have you tried setting the production=true option explicitly when you are creating the connection?

—A

**Comment by richardgirges** [comment]
I'm getting a node crash on Socket Disconnect (due to expired certificate).  We send pushes for multiple clients, so it'd be ideal if we could gracefully handle the expired cert error.

Another option would be if we could check the validity of the cert before attempting to make the connection.

Any advice?  

Here's what we're getting:

    SOCKET ERROR
    Disconnected from APNS

    /repo/pushqueue/node_modules/apn/node_modules/q/q.js:128
                    throw e;
                          ^
    Error: 140735085163264:error:14094415:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate expired:../deps/openssl/openssl/ssl/s3_pkt.c:1275:SSL alert number 45

    at SlabBuffer.use (tls.js:234:18)
    at CleartextStream.read [as _read] (tls.js:454:29)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at Socket.pipeOnReadable (_stream_readable.js:642:5)
    at Socket.emit (events.js:92:17)

**Comment by argon** [comment]
I'm working on cert validation code at the moment. Don't have an ETA as my time is limited but I hope to have released soon.

—A

**Comment by richardgirges** [comment]
Thanks for the heads up.  In the meantime, I've resorted to the following (ghetto) workaround (based on my limited knowledge of APNS and SSL):

    npm install execSync
    
    var sh = require('execSync');

	var certCheckData = sh.exec( 'openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert ' + certPath + ' -debug -showcerts -CAfile ' + caPath )

	var certCheckSTDOUT = certCheckData.stdout.toLowerCase();

	if ( certCheckSTDOUT.indexOf( 'expired' ) !== -1 || certCheckSTDOUT.indexOf( 'revoked' ) !== -1 ) {

        // bail
    }
    else {
        // open apn connection; send push 
    }

**Comment by argon** [comment]
v1.7.0 now has a certificate validator built in.
