### ISSUE TITLE
Error: socket hang up (Node Version: 10.35, Package Version: 1.6.2)

### ISSUE THREAD

**Issue by bigthyme** [argon/node-apn#244]
Upon trying to send 2000 notifications to fake "tokens" (i.e. self generated) sequentially from the same node process, I receive the following errors:

```
 apn Buffering 113 notifications for resending +3ms
  apn Socket closed +0ms 601
  apn Removing socket from pool +0ms 601
  apn Initialising connection +1ms
  apn 1399 left to send +0ms
  apn 1399 left to send +2ms
  apn Socket error occurred +193ms undefined { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
  apn Destroying connection +3ms undefined
  apn Removing socket from pool +0ms undefined
  apn Socket closed +1ms undefined
  apn Removing socket from pool +0ms undefined
  apn 1399 left to send +1ms
  apn Raising error: +1ms { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined } undefined undefined
  apn Error occurred with trace: +0ms Error: socket hang up
  at SecurePair.error (tls.js:1011:23)
  at EncryptedStream.CryptoStream._done (tls.js:703:22)
  at CleartextStream.read [as _read] (tls.js:499:24)
  at CleartextStream.Readable.read (_stream_readable.js:341:10)
  at EncryptedStream.onCryptoStreamFinish (tls.js:304:47)
  at EncryptedStream.g (events.js:180:16)
  at EncryptedStream.emit (events.js:117:20)
  at finishMaybe (_stream_writable.js:360:12)
  at endWritable (_stream_writable.js:367:3)
  at EncryptedStream.Writable.end (_stream_writable.js:345:5)
  at EncryptedStream.CryptoStream.end (tls.js:641:31)
  at Socket.onend (_stream_readable.js:502:10)
  at Socket.g (events.js:180:16)
  at Socket.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:442:13)
```

Here is my config object including the feedback options (i.e. `debug`):

```
{ 
  payLoadFilter: 'messageFrom',
  maxConnections: 3,
  cert: 'mycert.pem',
  key: 'mekey.pem',
  debug: { batchFeedback: false },
  passphrase: '<passphrase>',
  gateway: 'gateway.sandbox.push.apple.com',
  address: 'feedback.sandbox.push.apple.com' 
}
```

It's also important to note that I can get this error even when not connecting to Apple's feedback service.

**Comment by argon** [comment]
Are you using a feedback configuration when trying to send notifications? If I run the following code

```
var service = new apn.connection({
    address: 'feedback.sandbox.push.apple.com'
});

service.pushNotification(note, device);
```

Then I get exactly the same error because the configuration is forcing the module to connect to the feedback service instead of the gateway.

You should use the `production` flag to configure the connection then you will be able to share the configuration object between the feedback and connection.
