### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by urbanappetite** [argon/node-apn#251]
Hi,

I just updated to 1.7.3 and now get the following error:

```GMT apn TypeError: Cannot read property 'match' of undefined 
Mar 14 16:58:48 parenthoods-prod-new app/workerPushNotification.1:      at apnCertificateFromPem (/app/node_modules/apn/lib/credentials/parsePemCertificate.js:25:24) ```

Any ideas?

Thanks

Luke

**Comment by urbanappetite** [comment]
When I log the certificate, the feedback service outputs all the required variables including "type" but when sending a push notification, only the body is shown.

If I remove the check in parsePemCertificate.js at line 25 then the push notifications reach the devices however I get the following error:

```GMT apn Error: Cannot read X.509 certificate. ASN.1 object is not an X509v3 Certificate. 
at Object.pki.certificateFromAsn1 (/app/node_modules/apn/node_modules/node-forge/js/x509.js:1258:17) 
at apnCertificateFromPem (/app/node_modules/apn/lib/credentials/parsePemCertificate.js:30:36) 
at parse (/app/node_modules/apn/lib/credentials/parse.js:9:24) 
at /app/node_modules/apn/lib/connection.js:155:15 ```

**Comment by argon** [comment]
Would you be able to email me a copy of the certificate? Something definitely isn't right about the file format and I'd like to figure out where the problem lies.

\A

**Comment by argon** [comment]
Also, which OS and version of node.js are you using?

I can't find any code-path which would cause the error you're seeing, unless Regular Expressions are somehow broken(!)

**Comment by argon** [comment]
Closing due to inactivity.
