### ISSUE TITLE
Unable to send push even I got zero error

### ISSUE THREAD

**Issue by ezyclie** [argon/node-apn#289]
Hi,

Somehow I am facing really strange issue today with below log:
  apn Initialising connection +0ms
  apn Loading Credentials +1ms
  apn 1 left to send +2ms
  apn Connection established +822ms
[ '-------- LOG ------------',
  '[1437961711674]-->',
  [ 'Connected' ],
  '-------- end ------------' ]
  apn Socket drained +103ms 0
[ '-------- LOG ------------',
  '[1437961711777]-->',
  [ 'Notification transmitted to:3839a5c722f19d0827e2b571ecd4ebe5ee664e349ece7585e037998255681ccc' ],
  '-------- end ------------' ]
  apn 0 left to send +0ms
  apn 0 left to send +1ms

Everything seems okay by looking at the logs above but there is no push go through

**Comment by ezyclie** [comment]
I am getting below log after debugging further with pm2 logs:
TypeError: Cannot assign to read only property 'aps' of {"message":"Catur terima ga","nid":"DA1712EE-5AE9-4F04-AE4D-644EAE07778F","type":"12"}
    at Object.Notification.toJSON (/home/push-notification/node_modules/apn/lib/notification.js:500:20)
    at Object.stringify (native)
    at Object.Notification.compile (/home/push-notification/node_modules/apn/lib/notification.js:417:24)
    at Object.Notification.length (/home/push-notification/node_modules/apn/lib/notification.js:372:32)
    at Connection.validNotification (/home/push-notification/node_modules/apn/lib/connection.js:695:35)
    at Connection.pushNotification (/home/push-notification/node_modules/apn/lib/connection.js:719:12)
    at /home/push-notification/dist/server/api/broadcast/broadcast.apn.js:90:22
    at Array.forEach (native)
    at iOSAPN.notify (/home/push-notification/dist/server/api/broadcast/broadcast.apn.js:88:20)
    at iosNotify (/home/push-notification/dist/server/api/broadcast/broadcast.controller.js:82:9)
    at null._onTimeout (/home/push-notification/dist/server/api/broadcast/broadcast.controller.js:124:13)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by argon** [comment]
Could you post the code you are using to send the notification please. It looks like the notification object is not being created correctly somewhere.
