### ISSUE TITLE
Help to resolve this problem.

### ISSUE THREAD

**Issue by gorapa100** [argon/node-apn#293]
hi
I receive an error in the project.
What's the problem?
Please help to resolve this problem.

C:\pugaProject\PugaServer\node_modules\apn\node_modules\q\q.js:155
                throw e;
                      ^
Error: error:20075073:BIO routines:MEM_WRITE:null parameter
    at Object.exports.createCredentials (crypto.js:104:31)
    at Object.exports.connect (tls.js:1314:27)
    at apnSocketLegacy (C:\pugaProject\PugaServer\node_modules\apn\lib\socket.js
:36:19)
    at Connection.loadCredentials.then.done.terminated (C:\pugaProject\PugaServe
r\node_modules\apn\lib\connection.js:188:17)
    at _fulfilled (C:\pugaProject\PugaServer\node_modules\apn\node_modules\q\q.j
s:834:54)
    at self.promiseDispatch.done (C:\pugaProject\PugaServer\node_modules\apn\nod
e_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\pugaProject\PugaServer\node_modules\a
pn\node_modules\q\q.js:796:13)
    at C:\pugaProject\PugaServer\node_modules\apn\node_modules\q\q.js:604:44
    at runSingle (C:\pugaProject\PugaServer\node_modules\apn\node_modules\q\q.js
:137:13)
    at flush (C:\pugaProject\PugaServer\node_modules\apn\node_modules\q\q.js:125
:13)

**Comment by argon** [comment]
It looks like your certificates are bad. What process did you follow to create them?
