### ISSUE TITLE
ECONNRESET on sending notification

### ISSUE THREAD

**Issue by LukeeeeBennett** [argon/node-apn#296]
```
apn Initialising connection +7s
  apn 2 left to send +1ms
  apn Socket error occurred +2s undefined { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
  apn Destroying connection +0ms undefined
  apn Removing socket from pool +0ms undefined
  apn Raising error: +1ms { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } undefined undefined
  apn Error occurred with trace: +0ms Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
  apn Socket closed +0ms undefined
  apn Removing socket from pool +0ms undefined
```

I'm receiving these errors repeatedly after trying to send a push notification. It is in Sandbox mode.

Could anyone help? I swear this was working a month or so back.

**Comment by argon** [comment]
Are you running apn@1.7.4 or an older version? That looks a lot like the certificates are being rejected.

**Comment by LukeeeeBennett** [comment]
@argon - I updated my certificates and it was working wonderfully.

Now I am getting...

````
Fri, 14 Aug 2015 13:18:54 GMT apn Initialising connection
Fri, 14 Aug 2015 13:18:54 GMT apn Loading Credentials
Fri, 14 Aug 2015 13:18:54 GMT apn 1 left to send
Fri, 14 Aug 2015 13:18:54 GMT apn Connection established
Fri, 14 Aug 2015 13:18:54 GMT apn Socket drained 0
Fri, 14 Aug 2015 13:18:54 GMT apn 0 left to send
Fri, 14 Aug 2015 13:18:54 GMT apn 0 left to send
Fri, 14 Aug 2015 13:18:54 GMT apn Notification 0 caused an error: 8
Fri, 14 Aug 2015 13:18:54 GMT apn Raising error: 8 { encoding: 'utf8',
  payload: 
   { id: 1439558334,
     aps: { alert: 'Test' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"id":1439558334,"aps":{"alert":"test"}}',
  truncateAtWordEnd: false,
  _alert: 'test' } { token: <Buffer aa 91 bb 79 9b 0c bc 9c 2a c1 6a 1a 8a 95 f3 fe 5f 5c de fd eb bb bb d7 ab cd 74 98> }
Fri, 14 Aug 2015 13:18:54 GMT apn Buffering 0 notifications for resending
Fri, 14 Aug 2015 13:18:54 GMT apn Socket closed 0
Fri, 14 Aug 2015 13:18:54 GMT apn Removing socket from pool 0
Fri, 14 Aug 2015 13:18:54 GMT apn 0 left to send
````

**Comment by KorySumsion** [comment]
@argon @LukeeeeBennett - I am getting the same output. Did either of you find a solution to this problem?

**Comment by argon** [comment]
It looks like it's all working correctly to me.
