### ISSUE TITLE
Type Error: Bad Parameter, with production cert.pem and key.pem

### ISSUE THREAD

**Issue by gundlev** [argon/node-apn#309]
I have been working in development mode and it has been working just fine. I have switched over to production (set: process.env.NODE_ENV = 'production'; in js-file ), gotten production key.pem and cert.pem files and have also set the passphrase but its not working. Please help me.

I get the following error:
```
/Users/Niklas/Documents/iungo/NotificationServer/Server/node_modules/apn/node_modules/q/q.js:155
                throw e;
                      ^
TypeError: Bad parameter
    at TypeError (native)
    at Object.createSecureContext (_tls_common.js:106:19)
    at Object.exports.connect (_tls_wrap.js:850:21)
    at apnSocket (/Users/Niklas/Documents/iungo/NotificationServer/Server/node_modules/apn/lib/socket.js:56:19)
    at Connection.<anonymous> (/Users/Niklas/Documents/iungo/NotificationServer/Server/node_modules/apn/lib/connection.js:188:17)
    at _fulfilled (/Users/Niklas/Documents/iungo/NotificationServer/Server/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/Niklas/Documents/iungo/NotificationServer/Server/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/Niklas/Documents/iungo/NotificationServer/Server/node_modules/apn/node_modules/q/q.js:796:13)
    at /Users/Niklas/Documents/iungo/NotificationServer/Server/node_modules/apn/node_modules/q/q.js:604:44
    at runSingle (/Users/Niklas/Documents/iungo/NotificationServer/Server/node_modules/apn/node_modules/q/q.js:137:13)
```

**Comment by argon** [comment]
What code are you using to load the production keys and certificates? Are you passing the filenames to `new apn.Connection()`?

What version of node are you using?

**Comment by argon** [comment]
I have done some digging and it appears that the error is indicating that the passphrase you are providing is not a string. Have you supplied a number instead?

**Comment by gundlev** [comment]
Did supply a string but i must have done something wrong because i just wrote the options again and made absolutely sure it was a string and now it works. Thanks a lot!
