### ISSUE TITLE
crash with erroneous apm

### ISSUE THREAD

**Issue by Cactusbone** [argon/node-apn#313]
```
app/node_modules/q/q.js:155
                throw e;
                      ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.exports.createCredentials (crypto.js:131:17)
    at Object.exports.connect (tls.js:1345:27)
    at apnSocketLegacy (/app/node_modules/apn/lib/socket.js:36:19)
    at Feedback.loadCredentials.then.done.deferredConnection (/app/node_modules/apn/lib/feedback.js:165:17)
```

Looks like my PEM content is somehow invalid, but instead of getting that with `.on(error)` , i get a crash.
Can you try catch and send as event error ?

**Comment by Cactusbone** [comment]
my bad, I was missing a .on(error) on this particular feedback
