### ISSUE TITLE
Error: unable to parse credentials, incorrect passphrase when passphrase is correct

### ISSUE THREAD

**Issue by danieldaugherty** [argon/node-apn#336]
Hi @argon,
I'm having trouble connecting to APNs. When I try to send a push notification, I get this error:
```
    Error: mac verify failure
    at Error (native)
    at Object.createSecureContext (_tls_common.js:174:17)
    at Object.exports.connect (_tls_wrap.js:852:21)
    at apnSocket (/CBdrive/NodeJS/circleblack-js/node_modules/apn/lib/socket.js:56:19)
    at Connection.<anonymous> (/CBdrive/NodeJS/circleblack-js/node_modules/apn/lib/connection.js:199:17)
    at _fulfilled (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:796:13)
    at /CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:556:49
    at runSingle (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:137:13)
    at flush (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:125:13)
    at process._tickDomainCallback (node.js:381:11)
```
So I set DEBUG=apn. I didn't get any debug messages. I set NODE_ENV=production, and at least now, I'm getting the debug messages.
```
Wed, 09 Dec 2015 17:31:33 GMT apn Error: unable to parse credentials, incorrect passphrase
    at apnCredentialsFromPkcs12 (/CBdrive/NodeJS/circleblack-js/node_modules/apn/lib/credentials/parsePkcs12.js:34:10)
    at parse (/CBdrive/NodeJS/circleblack-js/node_modules/apn/lib/credentials/parse.js:11:21)
    at /CBdrive/NodeJS/circleblack-js/node_modules/apn/lib/connection.js:156:15
    at _fulfilled (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:796:13)
    at /CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:604:44
    at runSingle (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:137:13)
    at flush (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:125:13)
    at process._tickDomainCallback (node.js:381:11)
Wed, 09 Dec 2015 17:31:33 GMT apn Module initialisation error: [Error: mac verify failure]
Wed, 09 Dec 2015 17:31:33 GMT apn Raising error: 513 { encoding: 'utf8',
  payload:
   { title: 'Can I kick it?',
     id: 903175287,
     path: 'overview',
     aps:
      { badge: 1,
        sound: 'default',
        alert: 'Yes, you can!',
        'url-args': undefined,
        category: undefined } },
  expiry: 1449685893,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"title":"Can I kick it?","id":903175287,"path":"overview","aps":{"badge":1,"sound":"default","alert":"Yes, you can!"}}',
  truncateAtWordEnd: false,
  _badge: 1,
  _sound: 'default',
  _alert: 'Yes, you can!' } { token: <Buffer 8a b8 79 83 88 e1 f6 f2 58 a7 fc 75 8b 83 62 57 53 72 02 b4 92 be 8b c9 03 9c 5e 41 a5 d7 90 1d> }
```
The problem here is that I've already used this cert and passphrase combination to build the app with phonegap, so I know it's correct. Here's the push notification code:
```javascript
var service = new apn.Connection(
  "passphrase":"secret",
  "pfx":"/path/to/cert.p12",
  "production":false
});

apnNotification = new apn.Notification();
apnNotification.expiry = Math.floor(Date.now() / 1000) + 3600;
apnNotification.badge = 1;
apnNotification.sound = 'default';
apnNotification.alert = notification.message;
apnNotification.payload = {
  title: notification.title, id: notificationID, path: notification.path,
};

service.pushNotification(apnNotification, new apn.Device(notification.token));
```
The cert is a development certificate, but I never got the debug logging until I set NODE_ENV=production.

This is running on an AWS instance with CentOS 6.
Any help would be appreciated.

**Comment by argon** [comment]
Please verify the credentials with the following command:

    openssl pkcs12 -in /path/to/cert.p12 -nodes

```
Enter Import Password:
MAC Iteration 2048
MAC verified OK
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Certificate bag
[...]
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2048
[...]
```

Could you post here the lines that begin `PKCS7 Encrypted data` and `Shrouded Keybag` (only those two lines)

**Comment by danieldaugherty** [comment]
Thanks for your expedient reply.
Those two lines do not exist in the output.

**Comment by danieldaugherty** [comment]
Okay. So apparently, I was using a different cert than I meant to be. When using that command on the correct cert, we determined the passphrase we had wasn't working.

So we regenerated the cert, and this time the passphrase works (the lines you asked for are still not output by the command) and the notification is sent (yes!).

However, on connection, we're now getting this error:
```
Wed, 09 Dec 2015 19:39:09 GMT apn Error: multiple keys found in PFX/P12 file
    at /CBdrive/NodeJS/circleblack-js/node_modules/apn/lib/credentials/parsePkcs12.js:46:12
    at Array.forEach (native)
    at /CBdrive/NodeJS/circleblack-js/node_modules/apn/lib/credentials/parsePkcs12.js:43:25
    at Array.forEach (native)
    at apnCredentialsFromPkcs12 (/CBdrive/NodeJS/circleblack-js/node_modules/apn/lib/credentials/parsePkcs12.js:42:22)
    at parse (/CBdrive/NodeJS/circleblack-js/node_modules/apn/lib/credentials/parse.js:11:21)
    at /CBdrive/NodeJS/circleblack-js/node_modules/apn/lib/connection.js:156:15
    at _fulfilled (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:796:13)
    at /CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:604:44
    at runSingle (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:137:13)
    at flush (/CBdrive/NodeJS/circleblack-js/node_modules/apn/node_modules/q/q.js:125:13)
    at process._tickDomainCallback (node.js:381:11)
```
We generated the p12 file with just one cert/key, so this error is a bit confusing. What does it mean?
