### ISSUE TITLE
Unable to catch error thrown by validateCredentials

### ISSUE THREAD

**Issue by itsnotvalid** [argon/node-apn#338]
Below is snippet of sample code which loop over a bunch of certificates and connect to them (hopefully lazily)

```
let connection
for (let key of keys) {
  try {
    connection = this.connection = new apn.Connection(key.pushOptions)
  } catch (ex) {
    console.log(ex.message)
  }
}
```
apparently, when the cert has expired, or any other reason it could not be used, error would be thrown:

```
C:\mdm\node_modules\q\q.js:155
                throw e;
                ^

Error: certificate has expired: 2015-12-15T03:33:21.000Z
    at validateCredentials (C:\mdm\node_modules\apn\lib\credentials\validate.js:12:9)
    at C:\mdm\node_modules\apn\lib\connection.js:152:5
    at _fulfilled (C:\mdm\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\mdm\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\mdm\node_modules\q\q.js:796:13)
    at C:\mdm\node_modules\q\q.js:604:44
    at runSingle (C:\mdm\node_modules\q\q.js:137:13)
    at flush (C:\mdm\node_modules\q\q.js:125:13)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

Seems that those errors has to be *fulfilled* in the promise using code (inside this library in this case):
```
Q
.try(function () {
    if (!isConnectedToCloud()) {
        throw new Error("The cloud is down!");
    }

    return syncToCloud();
})
.catch(function (error) {
    console.error("Couldn't sync to the cloud", error);
});
```
(from Q's API, https://github.com/kriskowal/q/wiki/API-Reference)

That is, unless the original promise object is accessible, there seems to be no way of handling any error thrown.

I've not got time to write up pull requests as I am actually migrating my code out from using node.js due to various memory leaks in different libraries.

More reference: https://github.com/kriskowal/q/wiki/On-Exceptions

**Comment by itsnotvalid** [comment]
Oops I found the doc regarding error emission.
`connection.on('error', console.error)` fixed the problem.
