### ISSUE TITLE
Cannot call method 'key' of undefined

### ISSUE THREAD

**Issue by weechard** [argon/node-apn#358]
Hi, i have troubles sending APN. here are my codes. 

```
apnConnection = new apn.Connection({
        pfx: fs.readFileSync('./apn/Bluguard32ProAPN2016.p12'),
        ca: [fs.readFileSync('./apn/entrust_2048_ca.cer')],
        passphrase: 'Bluguard1234'
    });

    apnConnection16 = new apn.Connection({
        pfx: fs.readFileSync('./apn/BluguardAPN16ProductionKey.p12'),
        ca: [fs.readFileSync('./apn/entrust_2048_ca.cer')],
        passphrase: 'Bluguard1234'
    });
    
    apnConnectionDCod = new apn.Connection({
        cert: fs.readFileSync('./apn/DCodCert.pem'),
        key: fs.readFileSync('./apn/DCodKey.pem'),
        pfx: fs.readFileSync('./apn/DCodProAPNKey.p12'),
        ca: [fs.readFileSync('./apn/entrust_2048_ca.cer')],
        passphrase: 'Bluguard1234'
    });
    

apnConnection.pushNotification(note, device);
apnConnection16.pushNotification(note, device);
apnConnectionDCod.pushNotification(note, device);
```

The problem with this is that apnConnection failed to send APN meanwhile apnConnection16 & apnConnectionDCod has no problem.

i tried to run in DEBUG=apn mode. here are the errors shown.

```

Tue, 16 Feb 2016 04:43:37 GMT apn Module initialisation error: [TypeError: Cannot call method 'key' of undefined]
Tue, 16 Feb 2016 04:43:37 GMT apn Raising error: 513 { encoding: 'utf8',
  payload: 
   { device_id: 'B1FFFF',
     timestamp: 1455597817553,
     aps: 
      { badge: 1,
        sound: 'ping.aiff',
        alert: 'T32: P1 Disarmed by User 1' } },
  expiry: 1455601417,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'T32: P1 Disarmed by User 1',
  badge: 1,
  sound: 'ping.aiff',
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: true,
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined,
  compiledPayload: '{"device_id":"B1FFFF","timestamp":1455597817553,"aps":{"badge":1,"sound":"ping.aiff","alert":"T32: P1 Disarmed by User 1"}}' } { token: <Buffer fa 72 da fb cc 79 05 2c 66 e8 b4 fc b3 c7 d1 1c ee 9b 18 f7 a2 ca 58 45 80 61 5f 50 ec fa b7 c4> }
Notification caused error: 513 for device  { token: <Buffer fa 72 da fb cc 79 05 2c 66 e8 b4 fc b3 c7 d1 1c ee 9b 18 f7 a2 ca 58 45 80 61 5f 50 ec fa b7 c4> } { encoding: 'utf8',
  payload: 
   { device_id: 'B1FFFF',
     timestamp: 1455597817553,
     aps: 
      { badge: 1,
        sound: 'ping.aiff',
        alert: 'T32: P1 Disarmed by User 1' } },
  expiry: 1455601417,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'T32: P1 Disarmed by User 1',
  badge: 1,
  sound: 'ping.aiff',
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: true,
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined,
  compiledPayload: '{"device_id":"B1FFFF","timestamp":1455597817553,"aps":{"badge":1,"sound":"ping.aiff","alert":"T32: P1 Disarmed by User 1"}}' }
```

This is the error thrown.
```
/home/ubuntu/app/bluguard/node_modules/apn/node_modules/q/q.js:128
                    throw e;
                          ^
TypeError: Cannot call method 'key' of undefined
    at validateCredentials (/home/ubuntu/app/bluguard/node_modules/apn/lib/credentials/validate.js:4:52)
    at /home/ubuntu/app/bluguard/node_modules/apn/lib/connection.js:164:5
    at _fulfilled (/home/ubuntu/app/bluguard/node_modules/apn/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/home/ubuntu/app/bluguard/node_modules/apn/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/home/ubuntu/app/bluguard/node_modules/apn/node_modules/q/q.js:756:13)
    at /home/ubuntu/app/bluguard/node_modules/apn/node_modules/q/q.js:564:44
    at flush (/home/ubuntu/app/bluguard/node_modules/apn/node_modules/q/q.js:110:17)
    at process._tickCallback (node.js:442:13)
```

I'm running this on AWS EC2. Ubuntu 14.04.1 LTS

Any idea how to resolve this error ?

**Comment by weechard** [comment]
Solved the issue, something went wrong with my cert.
