### ISSUE TITLE
Get error when senden push

### ISSUE THREAD

**Issue by philipheinser** [argon/node-apn#359]
Server throws this error when I send push notifications sometimes it works sometimes it crashes.

```
2016-02-18T16:46:34.969105+00:00 app[web.1]:     at Error (native)
2016-02-18T16:46:34.969108+00:00 app[web.1]:     at Connection.<anonymous> (/app/node_modules/apn/lib/connection.js:199:17)
2016-02-18T16:46:34.969109+00:00 app[web.1]:     at _fulfilled (/app/node_modules/apn/node_modules/q/q.js:834:54)
2016-02-18T16:46:34.969110+00:00 app[web.1]:     at self.promiseDispatch.done (/app/node_modules/apn/node_modules/q/q.js:863:30)
2016-02-18T16:46:34.969110+00:00 app[web.1]:     at Promise.promise.promiseDispatch (/app/node_modules/apn/node_modules/q/q.js:796:13)
```

**Comment by argon** [comment]
Please give details about which version you're using and the configuration

**Comment by philipheinser** [comment]
I use version `"apn": "^1.7.5"`. node v4.3.1.

this is my code:
```
var agent = new apn.Connection({
          pfx: path,
          production: true
        });

var note = new apn.notification();
agent.pushNotification(note, token);
```

**Comment by philipheinser** [comment]
@argon This are the logs with the DEBUG=apn option

```
2016-02-18T16:55:36.232540+00:00 app[web.1]: Thu, 18 Feb 2016 16:55:36 GMT apn Initializing connection
2016-02-18T16:55:36.237431+00:00 app[web.1]: Thu, 18 Feb 2016 16:55:36 GMT apn 1 left to send
2016-02-18T16:55:36.245754+00:00 app[web.1]:     at Object.asn1.fromDer (/app/node_modules/apn/node_modules/node-forge/js/asn1.js:271:17)
2016-02-18T16:55:36.245757+00:00 app[web.1]:     at _fulfilled (/app/node_modules/apn/node_modules/q/q.js:834:54)
2016-02-18T16:55:36.245758+00:00 app[web.1]:     at self.promiseDispatch.done (/app/node_modules/apn/node_modules/q/q.js:863:30)
2016-02-18T16:55:36.245759+00:00 app[web.1]:     at Promise.promise.promiseDispatch (/app/node_modules/apn/node_modules/q/q.js:796:13)
2016-02-18T16:55:36.245759+00:00 app[web.1]:     at /app/node_modules/apn/node_modules/q/q.js:604:44
2016-02-18T16:55:36.253194+00:00 app[web.1]: Error: Unable to load BIO
2016-02-18T16:55:36.253203+00:00 app[web.1]:     at flush (/app/node_modules/apn/node_modules/q/q.js:125:13)
2016-02-18T16:55:36.253205+00:00 app[web.1]:     at process._tickDomainCallback (node.js:385:13)
2016-02-18T16:55:36.253205+00:00 app[web.1]:     at process.wrappedFunction (/app/node_modules/newrelic/lib/transaction/tracer/index.js:245:51)
```

**Comment by argon** [comment]
There seems to be a problem loading your certificates. What format are they in?

—A

**Comment by philipheinser** [comment]
@argon was a problem with the cert. thanks for your help.
