### ISSUE TITLE
GOT socketError { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }

### ISSUE THREAD

**Issue by modood** [argon/node-apn#381]
no notifications arrived !!!

env:
```
node: v0.10.38
npm: 2.9.0
apn: 1.7.5
```

Event Emitted:
```
1.  disconnected
    openSockets: 0
2.  socketError
    { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
```

code:
```javascript
#!/usr/bin/env node

var apn = require('apn');

var options = {
  pfx: './Certificates.p12',
  passphrase: 'balabala'
};

var apnConnection = new apn.Connection(options);

apnConnection.on('error', function (err) {
  console.log('[*] error');
  console.log(err);
})

apnConnection.on('socketError', function (err) {
  console.log('[*] socketError');
  console.log(err);
})

apnConnection.on('transmitted', function (notification, device) {
  console.log('[*] transmitted');
  console.log(notification);
  console.log(device);
})

apnConnection.on('completed', function () {
  console.log('[*] completed');
})

apnConnection.on('cacheTooSmall', function (sizeDifference) {
  console.log('[*] cacheTooSmall');
  console.log(sizeDifference);
})

apnConnection.on('connected', function (openSockets) {
  console.log('[*] connected');
  console.log(openSockets);
})

apnConnection.on('disconnected', function (openSockets) {
  console.log('[*] disconnected');
  console.log(openSockets);
})

apnConnection.on('timeout', function () {
  console.log('[*] timeout');
})

apnConnection.on('transmissionError', function (errorCode, notification, device) {
  console.log('[*] transmissionError');
  console.log(errorCode);
  console.log(notification);
  console.log(device);
})

var token = '879af626d**************************************************3a58d';
var myDevice = new apn.Device(token);

var note = new apn.Notification();
note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
note.badge = 3;
note.sound = "ping.aiff";
note.alert = "\uD83D\uDCE7 \u2709 You have a new message";
note.payload = {'messageFrom': 'Caroline'};

apnConnection.pushNotification(note, myDevice)

```

**Comment by argon** [comment]
Please run again with `DEBUG=apn` and post the output

**Comment by modood** [comment]
output
```
➜  migrate git:(master) ✗ export DEBUG=apn && ./untitled.js 
  apn Initialising connection +0ms
  apn Loading Credentials +2ms
  apn 1 left to send +3ms
  apn Socket error occurred +2s undefined { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
  apn Destroying connection +6ms undefined
  apn Removing socket from pool +0ms undefined
  apn Socket closed +1ms undefined
  apn Removing socket from pool +0ms undefined
[*] disconnected
0
  apn 1 left to send +1ms
  apn Raising error: +2ms { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined } undefined undefined
  apn Error occurred with trace: +0ms Error: socket hang up
    at SecurePair.error (tls.js:1011:23)
    at EncryptedStream.CryptoStream._done (tls.js:703:22)
    at CleartextStream.read [as _read] (tls.js:499:24)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:304:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:360:12)
    at endWritable (_stream_writable.js:367:3)
    at EncryptedStream.Writable.end (_stream_writable.js:345:5)
[*] socketError
{ [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
  apn Initialising connection +1s
  apn 1 left to send +1ms
  apn Socket error occurred +2s undefined { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
  apn Destroying connection +2ms undefined
  apn Removing socket from pool +0ms undefined
  apn Socket closed +1ms undefined
  apn Removing socket from pool +0ms undefined

```

**Comment by argon** [comment]
It looks like you are having trouble reading the Apple servers, this may be a problem with your connection to Apple, or a node.js bug.

Please convert your p12 file to `pem` and run the following command:

```
$ openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert cert.pem -key key.pem
```

**Comment by modood** [comment]
```
➜  migrate git:(master) ✗ openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert cert.pem -key key.pem
Enter pass phrase for key.pem:
CONNECTED(00000003)
depth=2 O = Entrust.net, OU = www.entrust.net/CPS_2048 incorp. by ref. (limits liab.), OU = (c) 1999 Entrust.net Limited, CN = Entrust.net Certification Authority (2048)
verify return:1
depth=1 C = US, O = "Entrust, Inc.", OU = www.entrust.net/rpa is incorporated by reference, OU = "(c) 2009 Entrust, Inc.", CN = Entrust Certification Authority - L1C
verify return:1
depth=0 C = US, ST = California, L = Cupertino, O = Apple Inc., CN = gateway.sandbox.push.apple.com
verify return:1
140629174048400:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
Certificate chain
 0 s:/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.sandbox.push.apple.com
   i:/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
 1 s:/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
   i:/O=Entrust.net/OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048)
---
```
