### ISSUE TITLE
{ [Error: socket hang up] code: 'ECONNRESET' }

### ISSUE THREAD

**Issue by jrgito** [argon/node-apn#386]
Hello, until now everything was working well but today has appeared this error and we cant send push
{ [Error: socket hang up] code: 'ECONNRESET' }

I dont know why? we have the same code from 5 or 6 months and was working well.
my code is this, very similar form your examples:
```
var cert = fs.readFileSync(config.app.push.apple.cert);
key = fs.readFileSync(config.app.push.apple.key);
var options = {
    cert: cert,
    certData: null,
    key: key,
    keyData: null,
    passphrase: 'fi1012',
    ca: null,
    pfx: null,
    pfxData: null,
    gateway: config.app.push.apple.gateway,
    port: 2195,
    rejectUnauthorized: true,
    enhanced: true,
    errorCallback: apnErrorCallback,
    cacheLength: 100,
    autoAdjustCache: true,
    connectionTimeout: 0
  };

var apnConnection = new apns.Connection(options);
apnConnection.on('error', log('error'));
apnConnection.on('transmitted', log('transmitted'));
apnConnection.on('timeout', log('timeout'));
apnConnection.on('connected', log('connected'));
apnConnection.on('disconnected', log('disconnected'));
apnConnection.on('socketError',  log('socketError'));
apnConnection.on('transmissionError', transmissionError('transmissionError'));
apnConnection.on('cacheTooSmall', log('cacheTooSmall'));
apnConnection.on('completed', end('completed'));``

var note = new apns.Notification();
note.expiry = Math.floor(Date.now() / 1000) + 3600;
note.badge = 1;
note.sound = 'ping.aiff';
note.alert = item.message;
note.payload = {'rid': 1};
apnConnection.pushNotification(note,item.token);
```
Note: item is the object that contains the token. 
Also I've tryed with :

```
var device = new apns.Device(item.token);
apnConnection.pushNotification(note,device);
```
but also not works
in debug mode show this::
```
  apn Option [certData] set to null. This may cause unexpected behaviour. +0ms
  apn Option [keyData] set to null. This may cause unexpected behaviour. +0ms
  apn Option [ca] set to null. This may cause unexpected behaviour. +1ms
  apn Option [pfx] set to null. This may cause unexpected behaviour. +0ms
  apn Option [pfxData] set to null. This may cause unexpected behaviour. +0ms
  apn Initialising connection +13ms
  apn Loading Credentials +1ms
  apn 1 left to send +2ms
  apn Socket error occurred +396ms undefined { [Error: socket hang up] code: 'ECONNRESET' }
  apn Destroying connection +1ms undefined
  apn Removing socket from pool +1ms undefined
  apn Raising error: +1ms { [Error: socket hang up] code: 'ECONNRESET' } undefined undefined
  apn Error occurred with trace: +0ms Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1093:19)
    at TLSSocket.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at TLSSocket.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
  apn Socket closed +0ms undefined
  apn Removing socket from pool +1ms undefined
  apn 1 left to send +0ms
apn Shutdown pending +604ms
```
Do you know why is the error and can I solve it?

Thanks in advance!!

**Comment by levinunnink** [comment]
Any word on this? I'm getting it to and it's pretty annoying.

**Comment by poloxue** [comment]
I think there are some invalid token! I suggest you delete invalid token (transmissionError event) before pushing notification!
