### ISSUE TITLE
Push not sended from server

### ISSUE THREAD

**Issue by Damassk** [argon/node-apn#391]
On server i have error 514

`514 { encoding: 'utf8',
  payload: 
   { aps: 
      { badge: 5,
        sound: undefined,
        alert: [Object],
        'url-args': undefined,
        category: undefined } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"aps":{"badge":5,"alert":{"title":"Biogram","body":"Final testing!"}}}',
  truncateAtWordEnd: false,
  _sound: undefined,
  _badge: 5,
  _alert: { title: 'Biogram', body: 'Финальное тестирование пушей!' } } { token: <Buffer 94 ae 48 97 6e 0c 0a 34 e0 5d 22 6a f5 ed 3d f5 a4 a0 6f fc 30 fb 54 e4 3e 18 11 b2 75 ef 0c 5e> }`

But on the local machine pushes sent without problems. I understand that the 514 error - a network error. What could cause this error?
On the server I have disabled the firewall. I also had access to port 2195 through telnet and nmap, access to the port 2195 is available.

debug on local 
Wed, 01 Jun 2016 12:15:30 GMT apn Initialising connection
Wed, 01 Jun 2016 12:15:30 GMT apn Loading Credentials
Wed, 01 Jun 2016 12:15:30 GMT apn 1 left to send
Wed, 01 Jun 2016 12:15:32 GMT apn Connection established
Wed, 01 Jun 2016 12:15:32 GMT apn Socket drained 0
Wed, 01 Jun 2016 12:15:32 GMT apn 0 left to send
Wed, 01 Jun 2016 12:15:32 GMT apn 0 left to send

debug on server
Wed, 01 Jun 2016 12:21:48 GMT apn Initialising connection
Wed, 01 Jun 2016 12:21:48 GMT apn Loading Credentials
Wed, 01 Jun 2016 12:21:48 GMT apn 1 left to send
Wed, 01 Jun 2016 12:21:58 GMT apn Socket error occurred undefined { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
Wed, 01 Jun 2016 12:21:58 GMT apn Raising error: { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined } null undefined
Wed, 01 Jun 2016 12:21:58 GMT apn Error occurred with trace: Error: socket hang up
    at SecurePair.error (tls.js:1011:23)
    at EncryptedStream.CryptoStream._done (tls.js:703:22)
    at EncryptedStream.read [as _read] (tls.js:495:12)
    at EncryptedStream.Readable.read (_stream_readable.js:341:10)
    at CleartextStream.onCryptoStreamFinish (tls.js:304:47)
    at CleartextStream.g (events.js:180:16)
    at CleartextStream.emit (events.js:92:17)
    at finishMaybe (_stream_writable.js:360:12)
    at endWritable (_stream_writable.js:367:3)
    at CleartextStream.Writable.end (_stream_writable.js:345:5)
    at CleartextStream.CryptoStream.end (tls.js:641:31)
    at Connection.<anonymous> (/home/s_user/biogram/biogram_server/node_modules/apn/lib/connection.js:227:17)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
Wed, 01 Jun 2016 12:21:58 GMT apn Destroying connection undefined
Wed, 01 Jun 2016 12:21:58 GMT apn Removing socket from pool undefined
Wed, 01 Jun 2016 12:21:58 GMT apn Raising error: [Error: Connect timed out] undefined undefined
Wed, 01 Jun 2016 12:21:58 GMT apn Error occurred with trace: Error: Connect timed out
    at Connection.<anonymous> (/home/s_user/biogram/biogram_server/node_modules/apn/lib/connection.js:225:35)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
Wed, 01 Jun 2016 12:21:58 GMT apn Socket closed undefined
Wed, 01 Jun 2016 12:21:58 GMT apn Removing socket from pool undefined
Wed, 01 Jun 2016 12:21:58 GMT apn 1 left to send

**Comment by argon** [comment]
Please try the following command on your server
```
$ openssl s_client -connect gateway.sandbox.push.apple.com:2195 -key <path-to-key-pem> -cert <path-to-cert-pem>
```
