### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by T-SEA** [argon/node-apn#423]
When I start node I get this error returned to me 

```
Error: certificate has expired: 2016-09-09T06:06:21.000Z
    at validateCredentials (/var/www/html/api/node_modules/apn/lib/credentials/validate.js:12:9)
    at /var/www/html/api/node_modules/apn/lib/feedback.js:132:5
    at _fulfilled (/var/www/html/api/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/var/www/html/api/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/var/www/html/api/node_modules/apn/node_modules/q/q.js:796:13)
    at /var/www/html/api/node_modules/apn/node_modules/q/q.js:604:44
    at runSingle (/var/www/html/api/node_modules/apn/node_modules/q/q.js:137:13)
    at flush (/var/www/html/api/node_modules/apn/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:419:13)
```

I tried adding `connection.on('error', console.error); `to feedback.js But that didnt work. I could find much info on this issue

**Comment by sorin** [comment]
same issue here

**Comment by santhoshreddyt** [comment]
Even I am getting same issue. Any way to solve this?

**Comment by argon** [comment]
Renew the certificate? I don't understand the issue here

**Comment by T-SEA** [comment]
Yes. lol. Renewing the certificate fixed the issue for me.

**Comment by santhoshreddyt** [comment]
I understand that renewing a certificate fixes the issue. But I am trying to handle that exception.

**Comment by argon** [comment]
@santhoshreddyt have you added an error handler to the feedback connection also?

**Comment by argon** [comment]
It's not coming from the connection
```
Error: certificate has expired: 2016-09-09T06:06:21.000Z
    at validateCredentials (/var/www/html/api/node_modules/apn/lib/credentials/validate.js:12:9)
=>  at /var/www/html/api/node_modules/apn/lib/feedback.js:132:5   <=====================
    at _fulfilled (/var/www/html/api/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/var/www/html/api/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/var/www/html/api/node_modules/apn/node_modules/q/q.js:796:13)
    at /var/www/html/api/node_modules/apn/node_modules/q/q.js:604:44
    at runSingle (/var/www/html/api/node_modules/apn/node_modules/q/q.js:137:13)
    at flush (/var/www/html/api/node_modules/apn/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:419:13)
```

**Comment by santhoshreddyt** [comment]
@argon  Yes I did not add error handler to feedback. I will try that. 
thanks

**Comment by rvislive** [comment]
But how to renew the certificate?

**Comment by slashcol** [comment]
> sí. jajaja. Renovar el certificado solucionó el problema.

hola amigo como renuevas el certificado?? tengo el mismo problema
