### ISSUE TITLE
aps import in NodeJS file Shows error (ver>2).

### ISSUE THREAD

**Issue by dhananjay972** [argon/node-apn#434]
i have successfully installed apn using npm install apn for linux but when i use var apn = require('apn');
in my server.js file it shows error as below
/home/User/node_modules/apn/index.js:5
});
^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/User/server/server.js:6:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by btelintelo** [comment]
I am seeing the same error in2.1.0.  Looks like notification/index.js has syntax errors in at least 2 places

**Comment by argon** [comment]
node-apn requires node v4 or above

**Comment by btelintelo** [comment]
rename apns.Connection to apns.Provider and remove apns.Device.  That fixed the error for me
